setup pre-commit hooks

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,19 @@
-npm run test
+echo "🐶 Running pre-commit checks..."
+
+# Exit immediately if a command exits with a non-zero status.
+set -e
+
+echo "👸 Linting and formatting staged files..."
+npx lint-staged || true
+
+echo "🤓 Generating types..."
+npx wrangler types
+
+echo "🧪 Running tests..."
+npm run test:husky
+
+echo "🏗️ Deploy dry run"
+npx wrangler deploy --dry-run
+
+echo "✅ Pre-commit checks passed!"
+exit 0
